### ISSUE TITLE
Suggestion: Press Escape to unfocus on current image

### ISSUE THREAD

**Issue by Spoonunit** [JonahGrimm/Meisunry#1]
Superb tool !. Thanks for creating it.

Appreciate you can click away from an image to un-focus, but I feel I want to hit Escape to unfocus.

**Comment by JonahGrimm** [comment]
That should be pretty easy to do.

**Comment by JonahGrimm** [comment]
Added feature in Meisunry 1.0.6 
https://github.com/JonahGrimm/Meisunry/releases/tag/v6

**Comment by Spoonunit** [comment]
Awesome. Thanks !
