### ISSUE TITLE
Suggestion: Watch/Monitor Folder for New Images

### ISSUE THREAD

**Issue by davidonabus** [JonahGrimm/Meisunry#2]
Love this app as-is.

One additional feature that would be great is the ability to monitor/watch the folder for new image additions.

**Comment by JonahGrimm** [comment]
Yeah, I'm planning on adding a refresh feature. Having some sort of watch system would be great too

**Comment by JonahGrimm** [comment]
https://github.com/JonahGrimm/Meisunry/releases/tag/v11
