### ISSUE TITLE
Option to only show images or videos from selected folder

### ISSUE THREAD

**Issue by epicstar7** [JonahGrimm/Meisunry#6]
Could you maybe add an option to be able to only show/filter images and/or videos instead of always showing all? When I choose a folder with a lot of photos and videos, especially loading all of those videos is making the pc really slow or not loading well/crashing. I want to be able to stop loading all the videos and only show images of that folder. Is this possible maybe? Thank you!

**Comment by JonahGrimm** [comment]
https://github.com/JonahGrimm/Meisunry/releases/tag/v10
